<link rel="stylesheet" href='<c:url value="/web-resources/css/custom.css"/>'>
<link rel="stylesheet" href='<c:url value="/web-resources/css/font-awesome-4.0.3/css/font-awesome.css"/>'>
<link rel="stylesheet" href='<c:url value="/web-resources/css/jquery-ui-1.10.4.custom.css"/>'>
<link rel="stylesheet" href='<c:url value="/web-resources/css/bootstrap.min.css"/>'>
<script type="text/javascript" src='<c:url value="/web-resources/js/lib/jquery-1.10.2.js"/>'></script>
<script type="text/javascript" src='<c:url value="/web-resources/js/lib/jquery-ui-1.10.4.custom.js"/>'></script>
<script type="text/javascript" src='<c:url value="/web-resources/js/lib/jquery.ui.datepicker.js"/>'></script>
<script type="text/javascript" src='<c:url value="/web-resources/js/lib/bootstrap.min.js"/>'></script>
<script type="text/javascript" src='<c:url value="/web-resources/js/lib/angular.js"/>'></script>
<script type="text/javascript" src='<c:url value="/web-resources/js/app.js"/>'></script>
<script type="text/javascript" src='<c:url value="/web-resources/js/js-movies.js"/>'></script>